language: node_js

node_js:
  - "8"

# 缓存依赖
cache:
  directories:
    - $HOME/.npm

before_install:
  - export TZ='Asia/Shanghai' # 更改时区

# 依赖安装
install:
  - npm install gitbook-cli -g
  # 安装gitbook插件
  - gitbook install

# 构建脚本
script:
  # 自定义输出目录 gitbook build src dest
  # - gitbook build . ./build/$CUSTOM_PATH
  - gitbook build . ./build

# 分支白名单
branches:
  only:
    - master

# GitHub Pages部署
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  #fqdn: $CUSTOM_DOMAIN
  name: $GIT_NAME
  email: $GIT_EMAIL
  on:
    branch: master
